# Generated by Django 4.1.3 on 2022-11-23 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 22, 19, 3, 42, 817234), verbose_name='Post Date'),
        ),
    ]
