# Generated by Django 4.1.3 on 2022-11-23 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 22, 18, 58, 19, 837816), verbose_name='Post Date'),
        ),
    ]
