# Generated by Django 4.1.3 on 2022-11-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(to='main_app.reaction'),
        ),
    ]
